version: "3.9"

services:

  api:
    build: .
    command: [
        "nodemon",
        "--exec",
        "dlv debug --accept-multiclient --api-version=2 --continue --headless --listen=:9001",
        "--ext",
        "go",
        "--legacy-watch",
        "--signal",
        "SIGHUP",
        "--watch",
        "/app",
        "./cmd/app.go",
    ]
    tty: true
    ports:
      - 9000:9000
      - 9001:9001
    restart: always
    volumes:
      - ./cmd:/app/cmd/
      - ./internal:/app/internal/
